### ISSUE TITLE
No Rain Sounds

### ISSUE THREAD

**Issue by YassaaaTU** [spaghettube/Eclectic_Sounds#2]
MC Version: 1.20.1
Modloader: Fabric

[Modlist](https://gist.github.com/YassaaaTU/a898c3660e7a2d7cc2fbeb8b7cd04c63)

**Comment by pocinhas** [comment]
damn ive been forgetting to check github my bad dude 💀 
i'll take a look and let you know, sorry for the wait D:

**Comment by pocinhas** [comment]
so i went over my resource pack and found no issues whatsover, tested in-game and the same. i also went over your modlist and there's no mod that messes with sounds/rain/water drops there (other than BRRP but i tested and its not that). what i will ask you is that you download the latest version which is R1.10 and if the issue is still present you send me a video (with audio, obviously) so i can see whats up.
try to copy this example video please:

https://github.com/spaghettube/Eclectic_Sounds/assets/101492556/59f4aedc-8b26-4e21-8961-52b1ddfcede2


also, dont forget to turn up weather volume in the sound menu for the video!

**Comment by YassaaaTU** [comment]
Hey I have long since deleted this modpack and I think it was probably a mod that was messing up your resource pack's sounds but got probably updated and fixed when you tested it. :)

**Comment by pocinhas** [comment]
alright, thanks for letting me know
